# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/wideBRAM/wideBRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM || ORIG_REF_NAME==wideBRAM}]

# IP: bd/wideBRAM/ip/wideBRAM_axi_bram_ctrl_0_0/wideBRAM_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_axi_bram_ctrl_0_0 || ORIG_REF_NAME==wideBRAM_axi_bram_ctrl_0_0}]

# IP: bd/wideBRAM/ip/wideBRAM_processing_system7_0_axi_periph_0/wideBRAM_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==wideBRAM_processing_system7_0_axi_periph_0}]

# IP: bd/wideBRAM/ip/wideBRAM_proc_sys_reset_0/wideBRAM_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_proc_sys_reset_0 || ORIG_REF_NAME==wideBRAM_proc_sys_reset_0}]

# IP: bd/wideBRAM/ip/wideBRAM_axi_mem_intercon_2/wideBRAM_axi_mem_intercon_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_axi_mem_intercon_2 || ORIG_REF_NAME==wideBRAM_axi_mem_intercon_2}]

# IP: bd/wideBRAM/ip/wideBRAM_xbar_4/wideBRAM_xbar_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_xbar_4 || ORIG_REF_NAME==wideBRAM_xbar_4}]

# IP: bd/wideBRAM/ip/wideBRAM_processing_system7_0_1_0/wideBRAM_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_processing_system7_0_1 || ORIG_REF_NAME==wideBRAM_processing_system7_0_1}]

# IP: bd/wideBRAM/ip/wideBRAM_axi_cdma_0_1/wideBRAM_axi_cdma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_axi_cdma_0_1 || ORIG_REF_NAME==wideBRAM_axi_cdma_0_1}]

# IP: bd/wideBRAM/ip/wideBRAM_blk_mem_gen_0_1/wideBRAM_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_blk_mem_gen_0_1 || ORIG_REF_NAME==wideBRAM_blk_mem_gen_0_1}]

# IP: bd/wideBRAM/ip/wideBRAM_auto_pc_6_0/wideBRAM_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_auto_pc_6 || ORIG_REF_NAME==wideBRAM_auto_pc_6}]

# IP: bd/wideBRAM/ip/wideBRAM_auto_ds_2_0/wideBRAM_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_auto_ds_2 || ORIG_REF_NAME==wideBRAM_auto_ds_2}]

# IP: bd/wideBRAM/ip/wideBRAM_auto_pc_7_0/wideBRAM_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_auto_pc_7 || ORIG_REF_NAME==wideBRAM_auto_pc_7}]

# IP: bd/wideBRAM/ip/wideBRAM_regFile_0_0/wideBRAM_regFile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_regFile_0_0 || ORIG_REF_NAME==wideBRAM_regFile_0_0}]

# IP: bd/wideBRAM/ip/wideBRAM_xbar_5_0/wideBRAM_xbar_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_xbar_5 || ORIG_REF_NAME==wideBRAM_xbar_5}]

# IP: bd/wideBRAM/ip/wideBRAM_auto_pc_8_2/wideBRAM_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_auto_pc_8 || ORIG_REF_NAME==wideBRAM_auto_pc_8}]

# IP: bd/wideBRAM/ip/wideBRAM_auto_ds_4_0/wideBRAM_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_auto_ds_4 || ORIG_REF_NAME==wideBRAM_auto_ds_4}]

# IP: bd/wideBRAM/ip/wideBRAM_auto_pc_9_2/wideBRAM_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_auto_pc_9 || ORIG_REF_NAME==wideBRAM_auto_pc_9}]

# IP: bd/wideBRAM/ip/wideBRAM_auto_pc_12/wideBRAM_auto_pc_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_auto_pc_12 || ORIG_REF_NAME==wideBRAM_auto_pc_12}]

# IP: bd/wideBRAM/ip/wideBRAM_auto_pc_13/wideBRAM_auto_pc_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_auto_pc_13 || ORIG_REF_NAME==wideBRAM_auto_pc_13}]

# IP: bd/wideBRAM/ip/wideBRAM_auto_ds_7/wideBRAM_auto_ds_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_auto_ds_7 || ORIG_REF_NAME==wideBRAM_auto_ds_7}]

# IP: bd/wideBRAM/ip/wideBRAM_auto_us_8/wideBRAM_auto_us_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_auto_us_8 || ORIG_REF_NAME==wideBRAM_auto_us_8}]

# XDC: bd/wideBRAM/ip/wideBRAM_axi_bram_ctrl_0_0/wideBRAM_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_proc_sys_reset_0/wideBRAM_proc_sys_reset_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==wideBRAM_proc_sys_reset_0 || ORIG_REF_NAME==wideBRAM_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/wideBRAM/ip/wideBRAM_proc_sys_reset_0/wideBRAM_proc_sys_reset_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==wideBRAM_proc_sys_reset_0 || ORIG_REF_NAME==wideBRAM_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/wideBRAM/ip/wideBRAM_proc_sys_reset_0/wideBRAM_proc_sys_reset_0_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_xbar_4/wideBRAM_xbar_4_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_processing_system7_0_1_0/wideBRAM_processing_system7_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==wideBRAM_processing_system7_0_1 || ORIG_REF_NAME==wideBRAM_processing_system7_0_1}] {/inst }]/inst ]]

# XDC: bd/wideBRAM/ip/wideBRAM_axi_cdma_0_1/wideBRAM_axi_cdma_0_1_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_axi_cdma_0_1/wideBRAM_axi_cdma_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==wideBRAM_axi_cdma_0_1 || ORIG_REF_NAME==wideBRAM_axi_cdma_0_1}] {/U0 }]/U0 ]]

# XDC: bd/wideBRAM/ip/wideBRAM_blk_mem_gen_0_1/wideBRAM_blk_mem_gen_0_1_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_auto_pc_6_0/wideBRAM_auto_pc_6_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_xbar_5_0/wideBRAM_xbar_5_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_auto_pc_8_2/wideBRAM_auto_pc_8_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_auto_ds_4_0/wideBRAM_auto_ds_4_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_auto_ds_4_0/wideBRAM_auto_ds_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==wideBRAM_auto_ds_4 || ORIG_REF_NAME==wideBRAM_auto_ds_4}] {/inst }]/inst ]]

# XDC: bd/wideBRAM/ip/wideBRAM_auto_pc_9_2/wideBRAM_auto_pc_9_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_auto_pc_12/wideBRAM_auto_pc_12_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_auto_pc_13/wideBRAM_auto_pc_13_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_auto_ds_7/wideBRAM_auto_ds_7_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_auto_ds_7/wideBRAM_auto_ds_7_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==wideBRAM_auto_ds_7 || ORIG_REF_NAME==wideBRAM_auto_ds_7}] {/inst }]/inst ]]

# XDC: bd/wideBRAM/ip/wideBRAM_auto_us_8/wideBRAM_auto_us_8_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_auto_us_8/wideBRAM_auto_us_8_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==wideBRAM_auto_us_8 || ORIG_REF_NAME==wideBRAM_auto_us_8}] {/inst }]/inst ]]

# XDC: bd/wideBRAM/wideBRAM_ooc.xdc
