# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/wideBRAM/wideBRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM || ORIG_REF_NAME==wideBRAM}]

# IP: bd/wideBRAM/ip/wideBRAM_auto_pc_6_0/wideBRAM_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_auto_pc_6 || ORIG_REF_NAME==wideBRAM_auto_pc_6}]

# IP: bd/wideBRAM/ip/wideBRAM_auto_ds_2_0/wideBRAM_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_auto_ds_2 || ORIG_REF_NAME==wideBRAM_auto_ds_2}]

# IP: bd/wideBRAM/ip/wideBRAM_auto_pc_7_0/wideBRAM_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_auto_pc_7 || ORIG_REF_NAME==wideBRAM_auto_pc_7}]

# IP: bd/wideBRAM/ip/wideBRAM_processing_system7_0_2/wideBRAM_processing_system7_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_processing_system7_0_2 || ORIG_REF_NAME==wideBRAM_processing_system7_0_2}]

# IP: bd/wideBRAM/ip/wideBRAM_axi_cdma_0_2/wideBRAM_axi_cdma_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_axi_cdma_0_2 || ORIG_REF_NAME==wideBRAM_axi_cdma_0_2}]

# IP: bd/wideBRAM/ip/wideBRAM_axi_bram_ctrl_0_1_0/wideBRAM_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_axi_bram_ctrl_0_1 || ORIG_REF_NAME==wideBRAM_axi_bram_ctrl_0_1}]

# IP: bd/wideBRAM/ip/wideBRAM_blk_mem_gen_0_2/wideBRAM_blk_mem_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_blk_mem_gen_0_2 || ORIG_REF_NAME==wideBRAM_blk_mem_gen_0_2}]

# IP: bd/wideBRAM/ip/wideBRAM_processing_system7_0_axi_periph_4/wideBRAM_processing_system7_0_axi_periph_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_processing_system7_0_axi_periph_4 || ORIG_REF_NAME==wideBRAM_processing_system7_0_axi_periph_4}]

# IP: bd/wideBRAM/ip/wideBRAM_proc_sys_reset_1_0/wideBRAM_proc_sys_reset_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_proc_sys_reset_1 || ORIG_REF_NAME==wideBRAM_proc_sys_reset_1}]

# IP: bd/wideBRAM/ip/wideBRAM_axi_mem_intercon_5/wideBRAM_axi_mem_intercon_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_axi_mem_intercon_5 || ORIG_REF_NAME==wideBRAM_axi_mem_intercon_5}]

# IP: bd/wideBRAM/ip/wideBRAM_xbar_10/wideBRAM_xbar_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_xbar_10 || ORIG_REF_NAME==wideBRAM_xbar_10}]

# IP: bd/wideBRAM/ip/wideBRAM_auto_pc_12/wideBRAM_auto_pc_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_auto_pc_12 || ORIG_REF_NAME==wideBRAM_auto_pc_12}]

# IP: bd/wideBRAM/ip/wideBRAM_auto_pc_13/wideBRAM_auto_pc_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wideBRAM_auto_pc_13 || ORIG_REF_NAME==wideBRAM_auto_pc_13}]

# XDC: bd/wideBRAM/ip/wideBRAM_auto_pc_6_0/wideBRAM_auto_pc_6_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_auto_ds_2_0/wideBRAM_auto_ds_2_ooc.xdc

# XDC: bd/wideBRAM/ip/wideBRAM_auto_ds_2_0/wideBRAM_auto_ds_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==wideBRAM_auto_ds_2 || ORIG_REF_NAME==wideBRAM_auto_ds_2}] {/inst }]/inst ]]

# XDC: bd/wideBRAM/ip/wideBRAM_auto_pc_7_0/wideBRAM_auto_pc_7_ooc.xdc

# XDC: bd/wideBRAM/wideBRAM_ooc.xdc
